name: Publish NPM Packages Script As Indpendent Version

 
on:
  push:
    branches:
      - main # Adjust this path to match your package directories
    paths:
      - packages/**/package.json

jobs:
    publish:
      name: Publish
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Setup Node
          uses: actions/setup-node@v2
          with:
            node-version: 20
            registry-url: 'https://npm.pkg.github.com'
        - name: Install
          run: yarn install --frozen-file
        - name: Publish
          run: |
            yarn lerna publish from-package --yes
          env:
            GH_TOKEN: ${{ secrets.GITHUB_REGISTRY_PACKGES_TOKEN }}
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_REGISTRY_PACKGES_TOKEN }}